In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import pandas as pd

# Always make it pretty.
plt.style.use('ggplot')

In [2]:
df1 = pd.read_csv("data/accidents_2005_to_2007.csv")
df2 = pd.read_csv("data/accidents_2009_to_2011.csv")
df3 = pd.read_csv("data/accidents_2012_to_2014.csv")
traffic = pd.read_csv("data/ukTrafficAADF.csv")

df12 = pd.concat([df1,df2])
df = pd.concat([df12,df3])

df = df.drop_duplicates(subset=['Accident_Index','Date','LSOA_of_Accident_Location','Time','Longitude','Latitude'], keep='first')

df = df[df.Speed_limit !=15]


/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1469953 entries, 0 to 464696
Data columns (total 33 columns):
Accident_Index                                 1469953 non-null object
Location_Easting_OSGR                          1469852 non-null float64
Location_Northing_OSGR                         1469852 non-null float64
Longitude                                      1469852 non-null float64
Latitude                                       1469852 non-null float64
Police_Force                                   1469953 non-null int64
Accident_Severity                              1469953 non-null int64
Number_of_Vehicles                             1469953 non-null int64
Number_of_Casualties                           1469953 non-null int64
Date                                           1469953 non-null object
Day_of_Week                                    1469953 non-null int64
Time                                           1469836 non-null object
Local_Authority_(District)           

In [4]:
del df['Police_Force']
del df['Local_Authority_(Highway)']
del df['Local_Authority_(District)']
del df['Pedestrian_Crossing-Human_Control']
del df['Pedestrian_Crossing-Physical_Facilities']
del df['Did_Police_Officer_Attend_Scene_of_Accident']

In [5]:
df.groupby(by='Year')['Number_of_Casualties'].sum()

Year
2005    271000
2006    258395
2007    247775
2009    222137
2010    208644
2011    203941
2012    195721
2013    183667
2014    194469
Name: Number_of_Casualties, dtype: int64

In [103]:
severity_totals = df.groupby('Accident_Severity').size().values
#total is 1,469,963 number of accidents 1469963
severity_mus = severity_totals / severity_totals.sum()
severity_mus

array([0.01295348, 0.13531997, 0.85172655])

In [104]:
# mu1 = 19041 / 1469963
# mu2 = 198914 / 1469963
# mu3 = 1252008 / 1469963

In [105]:
df.groupby(by='Year')['Number_of_Casualties'].sum()

Year
2005    271000
2006    258395
2007    247775
2009    222137
2010    208644
2011    203941
2012    195721
2013    183667
2014    194469
Name: Number_of_Casualties, dtype: int64

In [106]:
df.groupby(by='Year')['Number_of_Casualties'].sum()
# Year
# 2005    271008
# 2006    258403
# 2007    247779
# 2009    222145
# 2010    208647
# 2011    203943
# 2012    195721
# 2013    183668
# 2014    194474
# Name: Number_of_Casualties, dtype: int64

Year
2005    271000
2006    258395
2007    247775
2009    222137
2010    208644
2011    203941
2012    195721
2013    183667
2014    194469
Name: Number_of_Casualties, dtype: int64

In [107]:
df.groupby('Year').size()
# Year
# 2005    198722
# 2006    189157
# 2007    182114
# 2009    163550
# 2010    154411
# 2011    151466
# 2012    145569
# 2013    138657
# 2014    146317
# dtype: int64

# Year
# 2005    198727
# 2006    189160
# 2007    182114
# 2009    163553
# 2010    154413
# 2011    151467
# 2012    145569
# 2013    138658
# 2014    146319
# dtype: int64

Year
2005    198722
2006    189154
2007    182110
2009    163548
2010    154410
2011    151466
2012    145569
2013    138657
2014    146317
dtype: int64

In [108]:
df.describe()

Location_Easting_OSGR  Location_Northing_OSGR     Longitude  \
count           1.469852e+06            1.469852e+06  1.469852e+06   
mean            4.398986e+05            2.986709e+05 -1.432630e+00   
std             9.553436e+04            1.612566e+05  1.404316e+00   
min             6.495000e+04            1.029000e+04 -7.516225e+00   
25%             3.757500e+05            1.780075e+05 -2.363612e+00   
50%             4.409300e+05            2.653400e+05 -1.391624e+00   
75%             5.232900e+05            3.965962e+05 -2.184798e-01   
max             6.553700e+05            1.208800e+06  1.759398e+00   

           Latitude  Accident_Severity  Number_of_Vehicles  \
count  1.469852e+06       1.469953e+06        1.469953e+06   
mean   5.257593e+01       2.838773e+00        1.831847e+00   
std    1.452036e+00       4.014223e-01        7.152194e-01   
min    4.991294e+01       1.000000e+00        1.000000e+00   
25%    5.148790e+01       3.000000e+00        1.000000e+00   
50%    5.227670e+01       3.000000e+00        2.000000e+00   
75%    5.346434e+01       3.000000e+00        2.000000e+00   
max    6.075754e+01       3.000000e+00        6.700000e+01   

       Number_of_Casualties   Day_of_Week  1st_Road_Class  1st_Road_Number  \
count          1.469953e+06  1.469953e+06    1.469953e+06     1.469953e+06   
mean           1.350893e+00  4.118641e+00    4.089814e+00     1.008869e+03   
std            8.258039e-01  1.924708e+00    1.429888e+00     1.821697e+03   
min            1.000000e+00  1.000000e+00    1.000000e+00    -1.000000e+00   
25%            1.000000e+00  2.000000e+00    3.000000e+00     0.000000e+00   
50%            1.000000e+00  4.000000e+00    4.000000e+00     1.290000e+02   
75%            1.000000e+00  6.000000e+00    6.000000e+00     7.260000e+02   
max            9.300000e+01  7.000000e+00    6.000000e+00     9.999000e+03   

        Speed_limit  Junction_Detail  2nd_Road_Class  2nd_Road_Number  \
count  1.469953e+06              0.0    1.469953e+06     1.469953e+06   
mean   3.907870e+01              NaN    2.663982e+00     3.800913e+02   
std    1.417098e+01              NaN    3.207799e+00     1.300916e+03   
min    1.000000e+01              NaN   -1.000000e+00    -1.000000e+00   
25%    3.000000e+01              NaN   -1.000000e+00     0.000000e+00   
50%    3.000000e+01              NaN    3.000000e+00     0.000000e+00   
75%    5.000000e+01              NaN    6.000000e+00     0.000000e+00   
max    7.000000e+01              NaN    6.000000e+00     9.999000e+03   

       Urban_or_Rural_Area          Year  
count         1.469953e+06  1.469953e+06  
mean          1.356714e+00  2.009309e+03  
std           4.792170e-01  3.021197e+00  
min           1.000000e+00  2.005000e+03  
25%           1.000000e+00  2.006000e+03  
50%           1.000000e+00  2.010000e+03  
75%           2.000000e+00  2.012000e+03  
max           3.000000e+00  2.014000e+03

In [109]:
df.Weather_Conditions.value_counts()

Fine without high winds       1176642
Raining without high winds     172939
Other                           32914
Unknown                         27749
Raining with high winds         20359
Fine with high winds            18097
Snowing without high winds      11141
Fog or mist                      8053
Snowing with high winds          1933
Name: Weather_Conditions, dtype: int64

In [110]:
df.Accident_Severity.value_counts()

3    1251998
2     198914
1      19041
Name: Accident_Severity, dtype: int64

In [111]:
df.groupby(['Accident_Severity','Speed_limit']).sum()
severity_speed_limit = np.reshape(df.groupby(['Accident_Severity','Speed_limit']).size().values,(3,7))

severity_speed_limit[0]=severity_speed_limit[0]/severity_speed_limit[0].sum()
type(severity_speed_limit[0][0])

# severity_by_speed = ([(severity_speed_limit[0][:]/severity_speed_limit[0].sum()),
#                         (severity_speed_limit[1][:]/severity_speed_limit[1].sum()),
#                         (severity_speed_limit[2][:]/severity_speed_limit[2].sum())])
# severity_by_speed

numpy.int64

In [112]:
actuals_severity_slimits = np.transpose(np.reshape(df.groupby(['Accident_Severity','Speed_limit']).count()['Accident_Index'].values,(3,7)))
actuals_severity_slimits

array([[     2,      2,     10],
       [    95,   2341,  13995],
       [  6272, 116665, 819971],
       [  1761,  16279, 102233],
       [  1027,   7047,  39759],
       [  7380,  43719, 183831],
       [  2504,  12861,  92199]])

In [114]:
sums2 = df.groupby(['Accident_Severity','Speed_limit']).count().groupby('Accident_Severity').sum()['Accident_Index']
severity_sums = df.groupby(['Accident_Severity','Speed_limit']).count().groupby('Accident_Severity').sum()['Accident_Index'].values
severity_mus = severity_sums/severity_sums.sum()
severity_mus

array([0.01295348, 0.13531997, 0.85172655])

In [115]:
sums = df.groupby(['Speed_limit']).count()['Accident_Index']
slimit_sums = df.groupby(['Speed_limit']).count()['Accident_Index'].values
slimit_sums

array([    14,  16431, 942908, 120273,  47833, 234930, 107564])

In [138]:
# slimit10_expected = np.zeros(3)
# for i in np.arange(3):
#     expected_by_slimit[i][0] = slimit_sums[0] * severity_mus[i]
# slimit20_expected = np.zeros(3)
# for i in np.arange(3):
#     expected_by_slimit[i][1] = slimit_sums[1] * severity_mus[i]
# slimit30_expected = np.zeros(3)
# for i in np.arange(3):
#     expected_by_slimit[i][2] = slimit_sums[2] * severity_mus[i]
# slimit40_expected = np.zeros(3)
# for i in np.arange(3):
#     expected_by_slimit[i][3] = slimit_sums[3] * severity_mus[i]
# slimit50_expected = np.zeros(3)
# for i in np.arange(3):
#     expected_by_slimit[i][4] = slimit_sums[4] * severity_mus[i]
# slimit60_expected = np.zeros(3)
# for i in np.arange(3):
#     expected_by_slimit[i][5] = slimit_sums[5] * severity_mus[i]
# slimit70_expected = np.zeros(3)
# for i in np.arange(3):
#     expected_by_slimit[i][6] = slimit_sums[6] * severity_mus[i]
# slimit70_expected


expected_by_slimit = np.zeros((7,3))
for i in np.arange(7):
    for j in np.arange(3):
        expected_by_slimit[i][j] = slimit_sums[i] * severity_mus[j]
expected_by_slimit

array([[1.81348655e-01, 1.89447962e+00, 1.19241717e+01],
       [2.12838554e+02, 2.22344247e+03, 1.39947190e+04],
       [1.22139356e+04, 1.27594285e+05, 8.03099780e+05],
       [1.55795334e+03, 1.62753391e+04, 1.02439708e+05],
       [6.19603588e+02, 6.47276026e+03, 4.07406362e+04],
       [3.04315997e+03, 3.17907212e+04, 2.00096119e+05],
       [1.39332763e+03, 1.45555576e+04, 9.16151148e+04]])

In [137]:
#actual number of severity category 1, 2, 3, under speed limits...uh...10,20,30 &c
actuals_severity_slimits

array([[     2,      2,     10],
       [    95,   2341,  13995],
       [  6272, 116665, 819971],
       [  1761,  16279, 102233],
       [  1027,   7047,  39759],
       [  7380,  43719, 183831],
       [  2504,  12861,  92199]])

In [123]:
expected_by_slimit = expected_by_slimit.round().astype(int)
expected_by_slimit
expected_by_slimit.sum(axis=1)

array([    14,  16431, 942908, 120273,  47834, 234930, 107564])

In [136]:
i = 2
print( "actual", actuals_severity_slimits[i] )
print( "expected", expected_by_slimit[i] )
print( stats.chisquare( actuals_severity_slimits[i], expected_by_slimit[i] ) )

actual [  6272 116665 819971]
expected [ 12214 127594 803100]
Power_divergenceResult(statistic=4181.261949969622, pvalue=0.0)


In [139]:
pvalues = np.zeros(7)

# stats.chisquare(actuals_severity_slimits[0],expected_by_slimit[0])[1]

for i in np.arange(7):
    pvalues[i] = stats.chisquare(actuals_severity_slimits[i],expected_by_slimit[i])[1]

pvalues

# stats.chisquare(actuals_severity_slimits[2],expected_by_slimit[2])[1]
# actuals_severity_slimits[2]
# expected_by_slimit[2]


array([9.35193555e-005, 3.04293795e-016, 0.00000000e+000, 1.45514130e-006,
       4.31292023e-075, 0.00000000e+000, 1.25925683e-236])

In [34]:
mus = df.groupby(['Accident_Severity','Speed_limit']).count()['Accident_Index']/sums2
mus

Accident_Severity  Speed_limit
1                  10             0.000105
                   20             0.004989
                   30             0.329394
                   40             0.092485
                   50             0.053936
                   60             0.387585
                   70             0.131506
2                  10             0.000010
                   20             0.011769
                   30             0.586510
                   40             0.081839
                   50             0.035427
                   60             0.219788
                   70             0.064656
3                  10             0.000008
                   20             0.011178
                   30             0.654930
                   40             0.081656
                   50             0.031756
                   60             0.146830
                   70             0.073641
Name: Accident_Index, dtype: float64

In [35]:
df.Speed_limit.value_counts()

30    942908
60    234930
40    120273
70    107564
50     47833
20     16431
10        14
Name: Speed_limit, dtype: int64

In [ ]:
df.Light_Conditions.value_counts()

fig, ax = plt.subplots()

labels = 'Daylight', 'Dark/Lit', 'Dark', 'Unkown', 'Dark Unlit'

ax.pie(df.Light_Conditions.value_counts(), labels=labels)

In [ ]:
df.Road_Surface_Conditions.value_counts()

fig, ax = plt.subplots()

labels = 'Dry', 'Wet/Damp', 'Frost/Ice', 'Snow', 'Flood'

ax.pie(df.Road_Surface_Conditions.value_counts(), labels=labels)

In [ ]:
df.Carriageway_Hazards.value_counts()

In [ ]:
df.Urban_or_Rural_Area.value_counts()

fig, ax = plt.subplots(1,2)

labels = 'Urban', 'Rural', 'Other'

# ax.pie(df.Urban_or_Rural_Area.value_counts(), labels=labels)

urban = df[df["Urban_or_Rural_Area"] == 1]
rural = df[df["Urban_or_Rural_Area"] == 2]

labels = 'Dry', 'Wet/Damp', 'Frost/Ice', 'Snow', 'Flood'

ax[0].pie(urban.Road_Surface_Conditions.value_counts(), labels=labels)
ax[1].pie(rural.Road_Surface_Conditions.value_counts(), labels=labels)

In [ ]:
df.Special_Conditions_at_Site.value_counts()

In [ ]:
df.Road_Type.value_counts()

single= df[df["Road_Type"] == 'Single carriageway']
dual= df[df["Road_Type"] == 'Dual carriageway']
roundabout= df[df["Road_Type"] == 'Roundabout']
one_way= df[df["Road_Type"] == 'One way street']
slip= df[df["Road_Type"] == 'Slip road']

fig, ax = plt.subplots(2,3,figsize = (18,8))

labels = 'Dry', 'Wet/Damp', 'Frost/Ice', 'Snow', 'Flood'

ax[0][0].pie(single.Road_Surface_Conditions.value_counts(), labels=labels)
ax[0][1].pie(dual.Road_Surface_Conditions.value_counts(), labels=labels)
ax[0][2].pie(roundabout.Road_Surface_Conditions.value_counts(), labels=labels)
ax[1][0].pie(one_way.Road_Surface_Conditions.value_counts(), labels=labels)
ax[1][1].pie(slip.Road_Surface_Conditions.value_counts(), labels=labels)

ax[0][0].set_title('Single Carriageway')
ax[0][1].set_title('Dual Carriageway')
ax[0][2].set_title('Roundabout')
ax[1][0].set_title('One way street')
ax[1][1].set_title('Slip Road')

# Single carriageway    423414
# Dual carriageway       87274
# Roundabout             36637
# One way street         12434
# Slip road               5936
# Unknown                 4316

In [ ]:
limit20= df2[df2["Speed_limit"] == 20]
limit30= df2[df2["Speed_limit"] == 30]
limit40= df2[df2["Speed_limit"] == 40]
limit50= df2[df2["Speed_limit"] == 50]
limit60= df2[df2["Speed_limit"] == 60]
limit70= df2[df2["Speed_limit"] == 70]
count = {20:0,30:0,40:0,50:0,60:0,70:0}

for key, value in count.items():
    count[key] = len(df2[df2["Speed_limit"] == key].index)
    

slimit20= df[df["Speed_limit"] == 20]
slimit30= df[df["Speed_limit"] == 30]
slimit40= df[df["Speed_limit"] == 40]
slimit50= df[df["Speed_limit"] == 50]
slimit60= df[df["Speed_limit"] == 60]
slimit70= df[df["Speed_limit"] == 70]
counts = {20:0,30:0,40:0,50:0,60:0,70:0}

for key, value in counts.items():
    counts[key] = len(df[df["Speed_limit"] == key].index)
    
sslimit20= df3[df3["Speed_limit"] == 20]
sslimit30= df3[df3["Speed_limit"] == 30]
sslimit40= df3[df3["Speed_limit"] == 40]
sslimit50= df3[df3["Speed_limit"] == 50]
sslimit60= df3[df3["Speed_limit"] == 60]
sslimit70= df3[df3["Speed_limit"] == 70]
countss = {20:0,30:0,40:0,50:0,60:0,70:0}

for key, value in countss.items():
    countss[key] = len(df[df["Speed_limit"] == key].index)

fig, ax = plt.subplots(6,3,figsize = (18,24))

labels = 'Dry', 'Wet/Damp', 'Frost/Ice', 'Snow', 'Flood'

ax[0][0].pie(limit20.Road_Surface_Conditions.value_counts(), labels=labels)
ax[0][1].pie(limit30.Road_Surface_Conditions.value_counts(), labels=labels)
ax[0][2].pie(limit40.Road_Surface_Conditions.value_counts(), labels=labels)
ax[3][0].pie(limit50.Road_Surface_Conditions.value_counts(), labels=labels)
ax[3][1].pie(limit60.Road_Surface_Conditions.value_counts(), labels=labels)
ax[3][2].pie(limit70.Road_Surface_Conditions.value_counts(), labels=labels)

ax[0][0].set_title(f'Speed 20, n = {count[20]}')
ax[0][1].set_title(f'Speed 30, n = {count[30]}')
ax[0][2].set_title(f'Speed 40, n = {count[40]}')
ax[3][0].set_title(f'Speed 50, n = {count[50]}')
ax[3][1].set_title(f'Speed 60, n = {count[60]}')
ax[3][2].set_title(f'Speed 70, n = {count[70]}')

ax[1][0].pie(slimit20.Road_Surface_Conditions.value_counts(), labels=labels)
ax[1][1].pie(slimit30.Road_Surface_Conditions.value_counts(), labels=labels)
ax[1][2].pie(slimit40.Road_Surface_Conditions.value_counts(), labels=labels)
ax[4][0].pie(slimit50.Road_Surface_Conditions.value_counts(), labels=labels)
ax[4][1].pie(slimit60.Road_Surface_Conditions.value_counts(), labels=labels)
ax[4][2].pie(slimit70.Road_Surface_Conditions.value_counts(), labels=labels)

ax[1][0].set_title(f'Speed 20, n = {counts[20]}')
ax[1][1].set_title(f'Speed 30, n = {counts[30]}')
ax[1][2].set_title(f'Speed 40, n = {counts[40]}')
ax[4][0].set_title(f'Speed 50, n = {counts[50]}')
ax[4][1].set_title(f'Speed 60, n = {counts[60]}')
ax[4][2].set_title(f'Speed 70, n = {counts[70]}')

ax[2][0].pie(sslimit20.Road_Surface_Conditions.value_counts(), labels=labels)
ax[2][1].pie(sslimit30.Road_Surface_Conditions.value_counts(), labels=labels)
ax[2][2].pie(sslimit40.Road_Surface_Conditions.value_counts(), labels=labels)
ax[5][0].pie(sslimit50.Road_Surface_Conditions.value_counts(), labels=labels)
ax[5][1].pie(sslimit60.Road_Surface_Conditions.value_counts(), labels=labels)
ax[5][2].pie(sslimit70.Road_Surface_Conditions.value_counts(), labels=labels)

ax[2][0].set_title(f'Speed 20, n = {countss[20]}')
ax[2][1].set_title(f'Speed 30, n = {countss[30]}')
ax[2][2].set_title(f'Speed 40, n = {countss[40]}')
ax[5][0].set_title(f'Speed 50, n = {countss[50]}')
ax[5][1].set_title(f'Speed 60, n = {countss[60]}')
ax[5][2].set_title(f'Speed 70, n = {countss[70]}')


In [ ]:
df.Speed_limit.value_counts()

slimit20= df[df["Speed_limit"] == 20]
slimit30= df[df["Speed_limit"] == 30]
slimit40= df[df["Speed_limit"] == 40]
slimit50= df[df["Speed_limit"] == 50]
slimit60= df[df["Speed_limit"] == 60]
slimit70= df[df["Speed_limit"] == 70]
counts = {20:0,30:0,40:0,50:0,60:0,70:0}

for key, value in count.items():
    counts[key] = len(df[df["Speed_limit"] == key].index)

fig, ax = plt.subplots(2,3,figsize = (18,14))

fig.suptitle("Accident Severity by Speed limit")

labels = '3', '2', '1'

ax[0][0].pie(slimit20.Accident_Severity.value_counts(), labels=labels)
ax[0][1].pie(slimit30.Accident_Severity.value_counts(), labels=labels)
ax[0][2].pie(slimit40.Accident_Severity.value_counts(), labels=labels)
ax[1][0].pie(slimit50.Accident_Severity.value_counts(), labels=labels)
ax[1][1].pie(slimit60.Accident_Severity.value_counts(), labels=labels)
ax[1][2].pie(slimit70.Accident_Severity.value_counts(), labels=labels)

ax[0][0].set_title(f'Speed 20, n = {counts[20]}')
ax[0][1].set_title(f'Speed 30, n = {counts[30]}')
ax[0][2].set_title(f'Speed 40, n = {counts[40]}')
ax[1][0].set_title(f'Speed 50, n = {counts[50]}')
ax[1][1].set_title(f'Speed 60, n = {counts[60]}')
ax[1][2].set_title(f'Speed 70, n = {counts[70]}')

# 30    358591
# 60    101891
# 40     46288
# 70     44448
# 50     15666
# 20      3111
# 10         9
# 15         7
# Name: Speed_limit, dtype: int64

In [ ]:
df.groupby(['Accident_Severity','Speed_limit']).size()

In [ ]:
traffic.head()

In [ ]:
traffic.Road.value_counts()

In [ ]:
traffic.Northing.value_counts()

In [ ]:
traffic.Estimation_method_detailed.value_counts()

In [ ]:
x = np.arange(4).reshape((2,2))
x

In [ ]:
np.transpose(x)

In [ ]:
x