In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import pandas as pd
import functions as f

# Always make it pretty.
plt.style.use('ggplot')

In [2]:
df = f.load_and_clean_accident_data()

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3185: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  if (yield from self.run_code(code, result)):


In [3]:
# removing rows with road conditions that are too rare for me to analyze with significance
df = df[(df.Road_Surface_Conditions != 'Flood (Over 3cm of water)') & (df.Road_Surface_Conditions !='Snow')]

In [4]:
severity_mus = f.find_severity_mus(df)
severity_mus

array([0.01298477, 0.13558331, 0.85143192])

In [5]:
# rows correspond to varying road surface conditions, which are dry, iced/frosted, wet in rows 0,1,2 respectively
# columns correspond to severity 1, 2 and 3 in columns 0,1,2 respectively

actuals_severity_roadsc = np.transpose(np.reshape(df.groupby(['Accident_Severity','Road_Surface_Conditions']).count()['Accident_Index'].values,(3,3)))
actuals_severity_roadsc




array([[ 12751, 139816, 858938],
       [   317,   3523,  26809],
       [  5846,  54081, 353528]])

In [6]:
# rows correspond to varying road surface conditions, which are dry, iced/frosted, wet in rows 0,1,2 respectively
# columns correspond to severity 1, 2 and 3 in columns 0,1,2 respectively

actual_proportions = actuals_severity_roadsc / actuals_severity_roadsc.sum(axis=1).reshape((-1,1))
actual_proportions

array([[0.01260597, 0.13822571, 0.84916832],
       [0.01034291, 0.11494665, 0.87471043],
       [0.01413939, 0.13080263, 0.85505799]])

In [7]:
sums = df.groupby(['Road_Surface_Conditions']).count()['Accident_Index']
roadsc_sums = df.groupby(['Road_Surface_Conditions']).count()['Accident_Index'].values
roadsc_sums

array([1011505,   30649,  413455])

In [8]:
# rows correspond to varying road surface conditions, which are dry, iced/frosted, wet in rows 0,1,2 respectively
# columns correspond to severity 1, 2 and 3 in columns 0,1,2 respectively

expected_by_roadsc = f.calculate_expected_severities(severity_mus,roadsc_sums)
expected_by_roadsc

3   3


array([[ 13134, 137143, 861228],
       [   398,   4155,  26096],
       [  5369,  56058, 352029]])

In [9]:
# This code can be used to test whether the rounding is causing issues or not

# expected_by_roadsc = expected_by_roadsc.round().astype(int)
# expected_by_roadsc
# expected_by_roadsc.sum(axis=1)

In [11]:
p_values = f.calculate_p_values(actuals_severity_roadsc,expected_by_roadsc)
p_values

NameError: name 'zeros' is not defined