In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import pandas as pd
import functions as f

# Always make it pretty.
plt.style.use('ggplot')

In [2]:
df = f.load_and_clean_accident_data()



/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3185: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  if (yield from self.run_code(code, result)):


In [3]:
df = df[df.Speed_limit !=15]

In [4]:
severity_mus = f.find_severity_mus(df)
severity_mus

array([0.01295348, 0.13531997, 0.85172655])

In [5]:
actuals_severity_slimits = np.transpose(np.reshape(df.groupby(['Accident_Severity','Speed_limit']).count()['Accident_Index'].values,(3,7)))
actuals_severity_slimits

array([[     2,      2,     10],
       [    95,   2341,  13995],
       [  6272, 116665, 819971],
       [  1761,  16279, 102233],
       [  1027,   7047,  39759],
       [  7380,  43719, 183831],
       [  2504,  12861,  92199]])

In [6]:
sums = df.groupby(['Speed_limit']).count()['Accident_Index']
slimit_sums = df.groupby(['Speed_limit']).count()['Accident_Index'].values
slimit_sums

array([    14,  16431, 942908, 120273,  47833, 234930, 107564])

In [7]:
severity_mus

array([0.01295348, 0.13531997, 0.85172655])

In [8]:
slimit_sums

array([    14,  16431, 942908, 120273,  47833, 234930, 107564])

In [9]:
expected_by_slimit = np.dot(slimit_sums.reshape((-1,1)),severity_mus.reshape((1,-1)))
expected_by_slimit = expected_by_slimit.round().astype(int)

In [10]:
#actual number of severity category 1, 2, 3, under speed limits...uh...10,20,30 &c
actuals_severity_slimits

array([[     2,      2,     10],
       [    95,   2341,  13995],
       [  6272, 116665, 819971],
       [  1761,  16279, 102233],
       [  1027,   7047,  39759],
       [  7380,  43719, 183831],
       [  2504,  12861,  92199]])

In [11]:
# expected_by_slimit = expected_by_slimit.round().astype(int)
# expected_by_slimit
# expected_by_slimit.sum(axis=1)

In [12]:
f.calculate_p_values(actuals_severity_slimits,expected_by_slimit)

/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:4567: RuntimeWarning: divide by zero encountered in true_divide
  terms = (f_obs - f_exp)**2 / f_exp


array([[0.00000000e+000],
       [2.78462053e-016],
       [0.00000000e+000],
       [1.46361465e-006],
       [6.17893195e-075],
       [0.00000000e+000],
       [8.31846765e-237]])