In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import pandas as pd
import functions as f

# Always make it pretty.
plt.style.use('ggplot')

In [2]:
df = f.load_and_clean_accident_data()
df = df[(df.Weather_Conditions == 'Fine without high winds') | (df.Weather_Conditions =='Raining without high winds')]

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3185: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  if (yield from self.run_code(code, result)):


In [3]:
severity_mus = f.find_severity_mus(df)
severity_mus

array([0.01306099, 0.13703189, 0.84990712])

In [4]:
#actuals number of accidents of severity 0,1,2, (columns) and Weather conditions sunny (0) and rainy (1) rows
# actuals_severity_weather = df.groupby(['Accident_Severity','Weather_Conditions']).count()['Accident_Index']

actuals_severity_weather = np.transpose(np.reshape(df.groupby(['Accident_Severity','Weather_Conditions']).count()['Accident_Index'].values,(3,2)))
actuals_severity_weather

array([[ 15811, 164200, 996640],
       [  1816,  20737, 150387]])

In [5]:
sums = df.groupby(['Weather_Conditions']).count()['Accident_Index']
weather_sums = df.groupby(['Weather_Conditions']).count()['Accident_Index'].values
weather_sums

array([1176651,  172940])

In [6]:
expected_by_weather = np.dot(weather_sums.reshape((-1,1)),severity_mus.reshape((1,-1)))
expected_by_weather = expected_by_weather.round().astype(int)

# expected_by_weather = np.zeros((2,3))
# for i in np.arange(2):
#     for j in np.arange(3):
#         expected_by_weather[i][j] = weather_sums[i] * severity_mus[j]
# expected_by_weather

In [7]:
# expected_by_weather = expected_by_weather.round().astype(int)
# expected_by_weather
# expected_by_weather.sum(axis=1)

In [8]:
f.calculate_p_values(actuals_severity_weather,expected_by_weather)

# pvalues = np.zeros(2)

# # stats.chisquare(actuals_severity_slimits[0],expected_by_slimit[0])[1]

# for i in np.arange(2):
#     pvalues[i] = stats.chisquare(actuals_severity_weather[i],expected_by_weather[i])[1]

# pvalues

array([[8.00626198e-018],
       [4.77813285e-117]])